#!/bin/bash
#
# capture-mqtt-traffic.sh
#
# Captures MQTT traffic from integration tests and converts to test vectors.
# Creates binary files suitable for fuzzer corpus and unit test vectors.
#
# Usage:
#   ./scripts/capture-mqtt-traffic.sh [port] [output_dir]
#
# Prerequisites:
#   - tcpdump (with cap_net_raw capability or run as root)
#   - tshark (Wireshark CLI) for packet extraction
#   - mosquitto running on specified port
#
# Example:
#   # Terminal 1: Start capture
#   ./scripts/capture-mqtt-traffic.sh 31883 /tmp/mqtt-capture
#
#   # Terminal 2: Run integration tests
#   ./bin/api-test-mqtt-integration
#
#   # Press Ctrl+C to stop capture
#

set -e

PORT="${1:-31883}"
OUTPUT_DIR="${2:-/tmp/mqtt-capture}"
PCAP_FILE="${OUTPUT_DIR}/mqtt-traffic.pcap"
DURATION="${3:-60}"  # Capture duration in seconds

echo "MQTT Traffic Capture Tool"
echo "========================="
echo "Port:       $PORT"
echo "Output dir: $OUTPUT_DIR"
echo "Duration:   ${DURATION}s (or Ctrl+C to stop)"
echo ""

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Check for required tools
check_tool() {
    if ! command -v "$1" &> /dev/null; then
        echo "ERROR: $1 is required but not installed."
        echo "Install with: $2"
        exit 1
    fi
}

# tcpdump is primary capture tool
if command -v tcpdump &> /dev/null; then
    CAPTURE_TOOL="tcpdump"
elif command -v tshark &> /dev/null; then
    CAPTURE_TOOL="tshark"
else
    echo "ERROR: tcpdump or tshark required for packet capture"
    echo "Install tcpdump: apt install tcpdump"
    echo "Install tshark:  apt install tshark"
    exit 1
fi

echo "Using capture tool: $CAPTURE_TOOL"

# Cleanup on exit
cleanup() {
    echo ""
    echo "Stopping capture..."
    if [ -n "$CAPTURE_PID" ]; then
        kill "$CAPTURE_PID" 2>/dev/null || true
        wait "$CAPTURE_PID" 2>/dev/null || true
    fi
}
trap cleanup EXIT INT TERM

# Start packet capture
echo "Starting packet capture on port $PORT..."

if [ "$CAPTURE_TOOL" = "tcpdump" ]; then
    # Use tcpdump for capture
    tcpdump -i lo -w "$PCAP_FILE" "tcp port $PORT" &
    CAPTURE_PID=$!
else
    # Use tshark for capture
    tshark -i lo -w "$PCAP_FILE" -f "tcp port $PORT" &
    CAPTURE_PID=$!
fi

echo "Capture started (PID: $CAPTURE_PID)"
echo ""
echo "Run integration tests in another terminal:"
echo "  ./bin/api-test-mqtt-integration"
echo ""
echo "Press Ctrl+C when done..."

# Wait for capture to complete or user interrupt
sleep "$DURATION" || true

# Stop capture
cleanup

echo ""
echo "Processing captured packets..."

# Check if we got any packets
if [ ! -f "$PCAP_FILE" ] || [ ! -s "$PCAP_FILE" ]; then
    echo "No packets captured. Make sure:"
    echo "  1. mosquitto is running on port $PORT"
    echo "  2. Integration tests were run during capture"
    echo "  3. You have permission to capture on loopback"
    exit 1
fi

# Extract MQTT packets using tshark if available
if command -v tshark &> /dev/null; then
    echo "Extracting MQTT packets..."

    # Extract packet hex dumps
    tshark -r "$PCAP_FILE" -T fields -e mqtt.msgtype -e tcp.payload \
           -Y "mqtt" 2>/dev/null | head -20 > "${OUTPUT_DIR}/mqtt-packets.txt" || true

    # Create individual packet files for fuzzer corpus
    PACKET_NUM=0
    tshark -r "$PCAP_FILE" -T fields -e tcp.payload -Y "mqtt" 2>/dev/null | \
    while read -r hex_payload; do
        if [ -n "$hex_payload" ]; then
            # Remove colons and convert to binary
            echo "$hex_payload" | tr -d ':' | xxd -r -p > \
                "${OUTPUT_DIR}/packet_${PACKET_NUM}.bin" 2>/dev/null || true
            PACKET_NUM=$((PACKET_NUM + 1))
        fi
    done

    echo "Extracted packets to ${OUTPUT_DIR}/"
fi

# Create summary
echo ""
echo "Capture Summary:"
echo "----------------"
echo "PCAP file: $PCAP_FILE"
ls -la "$OUTPUT_DIR"/*.bin 2>/dev/null | wc -l | xargs -I {} echo "Packets extracted: {}"

# Generate C header with packet data
echo ""
echo "Generating C header file..."

cat > "${OUTPUT_DIR}/captured-packets.h" << 'HEADER_START'
/*
 * MQTT packets captured from integration tests
 * Auto-generated by capture-mqtt-traffic.sh
 */

#ifndef CAPTURED_MQTT_PACKETS_H
#define CAPTURED_MQTT_PACKETS_H

#include <stdint.h>
#include <stddef.h>

HEADER_START

PACKET_NUM=0
for binfile in "${OUTPUT_DIR}"/packet_*.bin; do
    if [ -f "$binfile" ]; then
        SIZE=$(stat -c%s "$binfile" 2>/dev/null || stat -f%z "$binfile" 2>/dev/null)
        if [ "$SIZE" -gt 0 ] && [ "$SIZE" -lt 1024 ]; then
            echo "" >> "${OUTPUT_DIR}/captured-packets.h"
            echo "/* Packet $PACKET_NUM - $SIZE bytes */" >> "${OUTPUT_DIR}/captured-packets.h"
            echo "static const uint8_t captured_pkt_${PACKET_NUM}[] = {" >> "${OUTPUT_DIR}/captured-packets.h"
            xxd -i < "$binfile" >> "${OUTPUT_DIR}/captured-packets.h"
            echo "};" >> "${OUTPUT_DIR}/captured-packets.h"
            PACKET_NUM=$((PACKET_NUM + 1))
        fi
    fi
done

echo "" >> "${OUTPUT_DIR}/captured-packets.h"
echo "#define CAPTURED_PACKET_COUNT $PACKET_NUM" >> "${OUTPUT_DIR}/captured-packets.h"
echo "" >> "${OUTPUT_DIR}/captured-packets.h"
echo "#endif /* CAPTURED_MQTT_PACKETS_H */" >> "${OUTPUT_DIR}/captured-packets.h"

echo "Generated: ${OUTPUT_DIR}/captured-packets.h"
echo ""
echo "To use captured packets:"
echo "  1. Copy ${OUTPUT_DIR}/*.bin to fuzzer corpus directory"
echo "  2. Include ${OUTPUT_DIR}/captured-packets.h in unit tests"
echo ""
echo "Done!"
